name: Python Tests and Quality Checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libbluetooth-dev pkg-config

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "Warning: Some requirements failed to install"
        pip install -r requirements-dev.txt
        pip install behave
        pip install -e .

    - name: Lint with flake8
      run: |
        flake8 fablab_visitor_logger tests

    - name: Check formatting with black
      run: |
        black --check .

    - name: Check imports with isort
      run: |
        isort --check-only --profile black .

    - name: Type check with mypy
      run: |
        mypy

    - name: Security check with bandit
      run: |
        bandit -r fablab_visitor_logger

    - name: Run unit tests
      run: |
        pytest --cov=fablab_visitor_logger tests/

    - name: Run BDD tests
      run: |
        behave tests/features/
