name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Install development dependencies
      run: |
        pip install -r requirements-dev.txt
        
    - name: Run linting and security checks
      run: |
        flake8 .
        black --check .
        isort --check .
        bandit -r .
        mypy .
        
    - name: Test with pytest
      run: |
        python -m pytest tests/ -v -m "not ble_required" --cov=.